---
- name: Restore the latest snapshot to EC2 instances
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Gather EC2 instance information
      ec2_instance_info:
        region: "{{ ec2_region }}"
        instance_ids: "{{ item }}"
      loop: "{{ ansible_play_hosts }}"
      register: ec2_info

    - name: Find latest snapshot for each instance
      ec2_snapshot_facts:
        region: "{{ ec2_region }}"
        filters:
          "description": "Automated Snapshot"
      register: snapshot_facts

    - name: Restore the latest snapshot to each instance
      ec2_vol:
        region: "{{ ec2_region }}"
        instance_id: "{{ item.instance_id }}"
        snapshot: "{{ snapshot_facts.snapshots | sort(attribute='start_time') | last }}"
        state: present
        volume_type: gp2
        device_name: /dev/sda1
      loop: "{{ ec2_info.results }}"
      loop_control:
        loop_var: item
      register: restore_results

    - name: Output restore results
      debug:
        var: restore_results