---
- name: Map hostnames to EC2 instance IDs
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather EC2 instance information based on tags or filters
      amazon.aws.ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          "tag:Name": "{{ inventory_hostname }}"
      register: ec2_info
      delegate_to: localhost

    - name: Set instance ID as a host fact
      set_fact:
        ec2_instance_id: "{{ ec2_info.instances[0].instance_id }}"

    - name: Debug output for instance ID
      debug:
        msg: "Instance ID for {{ inventory_hostname }} is {{ ec2_instance_id }}"
      delegate_to: localhost

- name: Create snapshots of EC2 instances
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather EC2 instance information
      amazon.aws.ec2_instance_info:
        region: "{{ ec2_region }}"
        instance_ids: "{{ ec2_instance_id }}"
      register: ec2_info
      delegate_to: localhost
      run_once: true

    - name: Ensure unique instance IDs
      set_fact:
        unique_instances: "{{ ec2_info.results | map(attribute='instance_id') | unique }}"

    - name: Create snapshots for each instance
      amazon.aws.ec2_snapshot:
        region: "{{ ec2_region }}"
        instance_id: "{{ ec2_instance_id }}"
        device_name: "{{ ec2_info.results | selectattr('instance_id', 'equalto', item) | map(attribute='root_device_name') | first }}"
        wait: true
      loop: "{{ unique_instances }}"
      loop_control:
        loop_var: item
      delegate_to: localhost

    - name: Output snapshot results
      debug:
        var: snapshot_results
      delegate_to: localhost