---
- name: Snapshot inventory hosts
  hosts: all
  gather_facts: false
  tasks:

    - name: Create ec2 snapshots for each instance
      amazon.aws.ec2_snapshot:
        region: "{{ hostvars[inventory_hostname]['placement']['region'] }}"
        instance_id: "{{ hostvars[inventory_hostname]['instance_id'] }}"
        device_name: "{{ hostvars[inventory_hostname]['root_device_name'] }}"
        wait: true
      register: snapshot_results
      delegate_to: localhost

    - name: Store latest snapshot ID as hostvar
      ansible.builtin.set_stats:
        latest_snapshot_id: "{{ snapshot_results.snapshot_id }}"

    - name: Output snapshot results
      ansible.builtin.debug:
        var: snapshot_results
      delegate_to: localhost
