---
- name: Snapshot inventory hosts
  hosts: all
  gather_facts: false
  tasks:

    - name: Create ec2 snapshots for each instance
      amazon.aws.ec2_snapshot:
        region: "{{ hostvars[inventory_hostname]['placement']['region'] }}"
        instance_id: "{{ hostvars[inventory_hostname]['instance_id'] }}"
        device_name: "{{ hostvars[inventory_hostname]['root_device_name'] }}"
        wait: true
        snapshot_tags:
          Host: "{{ inventory_hostname }}"
          InstanceId: "{{ hostvars[inventory_hostname]['instance_id'] }}"
          CreatedBy: "Ansible"
          DeleteAfter: "August 2024"
      register: snapshot_results
      delegate_to: localhost

    - name: Output snapshot results
      debug:
        var: snapshot_results
      delegate_to: localhost
