---
- name: Configure Windows Update to use WSUS
  hosts: all
  tasks:
    - name: Set WSUS server URL
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
        name: WUServer
        data: "{{ wsus_url }}"

    - name: Set WSUS target group
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: TargetGroup
        data: "{{ wsus_target_group }}"
